//
//  HTTPHeader+Defaults.swift
//  Network
//
//  Created by Chang Woo Son on 6/21/24.
//

import Foundation

// MARK: - Defaults

extension HTTPHeaders {
    /// The default set of `HTTPHeaders` attached to every `APIDefinition`
    /// request. Includes `Accept-Encoding`, `Accept-Language`, and
    /// `User-Agent` derived from the current process.
    public static var `default`: HTTPHeaders {
        [
            .defaultAcceptEncoding,
            .defaultAcceptLanguage,
            .defaultUserAgent,
        ]
    }
}

extension HTTPHeader {
    /// The library default `Accept-Encoding` header, covering the encodings
    /// supported by the current platform.
    ///
    /// See the [Accept-Encoding HTTP header documentation](https://tools.ietf.org/html/rfc7230#section-4.2.3) .
    public static let defaultAcceptEncoding: HTTPHeader = {
        let encodings: [String]
        if #available(iOS 11.0, macOS 10.13, tvOS 11.0, watchOS 4.0, *) {
            encodings = ["br", "gzip", "deflate"]
        } else {
            encodings = ["gzip", "deflate"]
        }

        return .acceptEncoding(encodings.qualityEncoded())
    }()

    /// The library default `Accept-Language` header, generated by querying
    /// `Locale` for the user's `preferredLanguages`.
    ///
    /// See the [Accept-Language HTTP header documentation](https://tools.ietf.org/html/rfc7231#section-5.3.5).
    public static var defaultAcceptLanguage: HTTPHeader {
        makeDefaultAcceptLanguage(preferredLanguages: Locale.preferredLanguages)
    }

    /// Builds a default `Accept-Language` header from an explicit preferred
    /// language list. Useful for tests and clients that own locale selection
    /// outside `Locale.preferredLanguages`.
    public static func makeDefaultAcceptLanguage(preferredLanguages: [String]) -> HTTPHeader {
        .acceptLanguage(preferredLanguages.prefix(6).qualityEncoded())
    }

    /// The library default `User-Agent` header, derived from the running
    /// process and platform.
    ///
    /// See the [User-Agent header documentation](https://tools.ietf.org/html/rfc7231#section-5.5.3).
    ///
    /// Example: `MyApp/1.0 (com.example.MyApp; build:1; iOS 18.0.0)`
    public static var defaultUserAgent: HTTPHeader {
        makeDefaultUserAgent(bundle: .main)
    }

    /// Builds a default `User-Agent` header from an explicit bundle.
    public static func makeDefaultUserAgent(bundle: Bundle) -> HTTPHeader {
        let info = bundle.infoDictionary
        let executable =
            (info?["CFBundleExecutable"] as? String)
            ?? (ProcessInfo.processInfo.arguments.first?.split(separator: "/").last.map(String.init)) ?? "Unknown"
        let bundle = info?["CFBundleIdentifier"] as? String ?? "Unknown"
        let appVersion = info?["CFBundleShortVersionString"] as? String ?? "Unknown"
        let appBuild = info?["CFBundleVersion"] as? String ?? "Unknown"

        let osNameVersion: String = {
            let version = ProcessInfo.processInfo.operatingSystemVersion
            let versionString = "\(version.majorVersion).\(version.minorVersion).\(version.patchVersion)"
            let osName: String = {
                #if os(iOS)
                #if targetEnvironment(macCatalyst)
                return "macOS(Catalyst)"
                #else
                return "iOS"
                #endif
                #elseif os(watchOS)
                return "watchOS"
                #elseif os(tvOS)
                return "tvOS"
                #elseif os(macOS)
                #if targetEnvironment(macCatalyst)
                return "macOS(Catalyst)"
                #else
                return "macOS"
                #endif
                #elseif swift(>=5.9.2) && os(visionOS)
                return "visionOS"
                #elseif os(Linux)
                return "Linux"
                #elseif os(Windows)
                return "Windows"
                #elseif os(Android)
                return "Android"
                #else
                return "Unknown"
                #endif
            }()

            return "\(osName) \(versionString)"
        }()

        let userAgent = "\(executable)/\(appVersion) (\(bundle); build:\(appBuild); \(osNameVersion))"

        return .userAgent(userAgent)
    }
}

extension Collection<String> {
    func qualityEncoded() -> String {
        enumerated().map { index, encoding in
            let quality = Swift.min(1.0, Swift.max(0.0, 1.0 - (Double(index) * 0.1)))
            guard quality < 1 else { return encoding }
            return "\(encoding);q=\(formattedQualityValue(quality))"
        }.joined(separator: ", ")
    }
}

private func formattedQualityValue(_ quality: Double) -> String {
    var formatted = String(format: "%.3f", locale: Locale(identifier: "en_US_POSIX"), quality)
    while formatted.last == "0" {
        formatted.removeLast()
    }
    if formatted.last == "." {
        formatted.removeLast()
    }
    return formatted
}
